# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'root.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Root_Form(object):
    def setupUi(self, Root_Form):
        Root_Form.setObjectName("Root_Form")
        Root_Form.resize(370, 230)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Root_Form.sizePolicy().hasHeightForWidth())
        Root_Form.setSizePolicy(sizePolicy)
        Root_Form.setMinimumSize(QtCore.QSize(370, 230))
        Root_Form.setMaximumSize(QtCore.QSize(370, 230))
        self.exit_btn = QtWidgets.QPushButton(Root_Form)
        self.exit_btn.setGeometry(QtCore.QRect(230, 180, 131, 41))
        self.exit_btn.setObjectName("exit_btn")
        self.new_window_btn = QtWidgets.QPushButton(Root_Form)
        self.new_window_btn.setGeometry(QtCore.QRect(230, 130, 131, 41))
        self.new_window_btn.setObjectName("new_window_btn")
        self.label = QtWidgets.QLabel(Root_Form)
        self.label.setGeometry(QtCore.QRect(70, 40, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setAutoFillBackground(False)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setOpenExternalLinks(True)
        self.label.setObjectName("label")
        self.btn3 = QtWidgets.QPushButton(Root_Form)
        self.btn3.setGeometry(QtCore.QRect(10, 180, 131, 41))
        self.btn3.setObjectName("btn3")

        self.retranslateUi(Root_Form)
        self.exit_btn.clicked.connect(Root_Form.close)
        QtCore.QMetaObject.connectSlotsByName(Root_Form)

    def retranslateUi(self, Root_Form):
        _translate = QtCore.QCoreApplication.translate
        Root_Form.setWindowTitle(_translate("Root_Form", "Form"))
        self.exit_btn.setText(_translate("Root_Form", "Exit"))
        self.new_window_btn.setText(_translate("Root_Form", "New Form"))
        self.label.setText(_translate("Root_Form", "waiting for params"))
        self.btn3.setText(_translate("Root_Form", "customEvne"))
